import "./globals.css";
import '@ant-design/v5-patch-for-react-19';

export const metadata = {
  title: "Nareswari Galeri",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
