import "./globals.css";
import 'antd/dist/reset.css';
import '@ant-design/v5-patch-for-react-19';
import Tracker from '@/components/microproses/Tracker';
import DiskonRefresh from '@/components/microproses/DiskonRefresh';

export const metadata = {
  title: "Nareswari Galeri",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Tracker />
        <DiskonRefresh />
        {children}
      </body>
    </html>
  );
}
